name: Sample SSH server workflow

on:
  workflow_dispatch:

jobs:
  sample:
    name: Sample
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Start SSH server
      timeout-minutes: 10
      uses: ./action.yml
      with:
        ngrok-authtoken: "${{ secrets.NGROK_AUTHTOKEN }}"
        ssh-public-key: "${{ secrets.SSH_PUBLIC_KEY }}"
