name: Sample SSH server workflow

on:
  workflow_dispatch:
    inputs:
      timeout:
        description: 'How long to run (minutes)'
        required: false
        type: number
        default: "10"

jobs:
  sample:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Start SSH server
      timeout-minutes: ${{ fromJSON(inputs.timeout) }}
      uses: jarlob/ssh-server-action@newversion
      with:
        ngrok-authtoken: "${{ secrets.NGROK_AUTHTOKEN }}"
        ssh-public-key: "${{ secrets.SSH_PUBLIC_KEY }}"
