name: Sample SSH server workflow

on:
  workflow_dispatch:
    inputs:
      time:
        description: 'How long to run (minutes)'
        required: true
        default: "10"

jobs:
  sample:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Start SSH server
      timeout-minutes: ${{ github.event.inputs.time }}
      uses: JarLob/ssh-server-action@patch1
      with:
        ngrok-authtoken: "${{ secrets.NGROK_AUTHTOKEN }}"
        ssh-public-key: "${{ secrets.SSH_PUBLIC_KEY }}"
