name: Sample SSH server workflow

on:
  workflow_dispatch:
    inputs:
      os:
        description: 'OS'
        required: true
        default: 'macos-latest'
        type: choice
        options:
          - windows-latest
          - macos-latest
          - ubuntu-latest
      timeout:
        description: 'How long to run (minutes)'
        required: false
        type: number
        default: "10"

jobs:
  sample:
    runs-on: ${{ inputs.os }}
    steps:
    - uses: actions/checkout@v4
    - name: Start SSH server
      timeout-minutes: ${{ fromJSON(inputs.timeout) }}
      uses: jarlob/ssh-server-action@windows2
      with:
        ngrok-authtoken: "${{ secrets.NGROK_AUTHTOKEN }}"
        ssh-public-key: "${{ secrets.SSH_PUBLIC_KEY }}"
