name: Sample SSH server workflow

on:
  workflow_dispatch:
    inputs:
      time:
        description: 'How long to run (minutes)'
        required: true
        type: number
        default: 10

jobs:
  sample:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Start SSH server
      timeout-minutes: ${{ inputs.time }}
      uses: mdelillo/ssh-server-action@75213802a040222dac486c62c30456c17fdc2413
      with:
        ngrok-authtoken: "${{ secrets.NGROK_AUTHTOKEN }}"
        ssh-public-key: "${{ secrets.SSH_PUBLIC_KEY }}"
