name: Sample SSH server workflow

on:
  workflow_dispatch:
    inputs:
      time:
        description: 'How many minutes to run'
        required: false
        default: "10"

jobs:
  sample:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Start SSH server
      timeout-minutes: 5
      uses: ./.github/actions
      with:
        ngrok-authtoken: "${{ secrets.NGROK_AUTHTOKEN }}"
        ssh-public-key: "${{ secrets.SSH_PUBLIC_KEY }}"
